### ISSUE TITLE
New form of file compression?

### ISSUE THREAD

**Issue by ghost** [kwsch/GARCTool#1]
Can this be used as an alternate way of creating files and uploading them to the internet, downloading them and extracting them (a more condensed and effective way that .rar or .zip files)?

**Comment by kwsch** [comment]
Sure, but there really is no compression.

Some files in a GARC may be lz11 compressed, but a .rar's best compression allows for better compression. You can use it to sneakily send/repackage files, but in terms of filesize you're not really getting anywhere.
