### ISSUE TITLE
Harmoknight GARC

### ISSUE THREAD

**Issue by KekMcGee** [kwsch/GARCTool#3]
I know this is probably dead but would there be a chance at adding support for Harmoknight GARCs?

Here are a few samples https://mega.nz/#!o1gnhLCL!k_MoSQkWwZnZ0oBx7kCkoQsLR_MNiy-XLp-t2si3SIg

**Comment by kwsch** [comment]
Game Freak uses the GARC format between their different IP but with different version IDs; these garcs have a version ID of 0x0204, which is not the same as the ones used in Pokémon.

pk3DS has absorbed this tool's functionality -- it's best to use that source code as a base instead. However, pk3DS is for Pokémon only (as was this tool). 

There's a few more differences in the format, but it's not something I'm interested in implementing for either tool as they aren't intended to handle every GARC format... only Pokémon ones :)
