### ISSUE TITLE
Need help for garc file.

### ISSUE THREAD

**Issue by benladen** [kwsch/GARCTool#4]
Please see https://gbatemp.net/threads/help-harmo-knight-garc-file-pack-unpack.456058/
It is about Harmo Knight garc file pack&unpack.

**Comment by kwsch** [comment]
GARCTool is only set up for Version 4 (0x0400) GARC files, which does not include the Harmo Knight format. 

I have no interest in adding such functionality to this tool or pk3DS; this repository has had no changes in the past 2 years.
