### ISSUE TITLE
cant decompress bin file

### ISSUE THREAD

**Issue by patritha** [kwsch/GARCTool#7]
when trying to decompress a bin file for tomodachi life, it errors out. this is the error
![error](https://github.com/user-attachments/assets/56a89912-c5bf-421b-8309-d7c8617bd3c6)

**Comment by kwsch** [comment]
If specific games have specific lz compression formats, then the program won't be able to handle them. You'd need to find a different tool.

**Comment by patritha** [comment]
do you reccomend anyhing for tomodachi life?

**Comment by kwsch** [comment]
Nope.
